### ISSUE TITLE
Lottery - isHeAWinner

### ISSUE THREAD

**Issue by thiivalente** [AcademyIFCE/TotoShow#5]
Quando a função é chamada sem passar o required o valor fica nil, logo quando é iniciada ela pega o valor do requiredBalls que é 0, caso chame a função sem chamar antes beginDraft, portanto tive que colocar no construtor da classe para resolver temporariamente.
Exemplo:
`init(range: CountableClosedRange<Int>) {
        self.lotteryRange = range
        self.requiredBalls = range.count/3
    }`

Obs: é importante criar um construtor que receba a quantidade de bolas necessárias para ganhar.

**Comment by trastoan** [comment]
Resolvido, o construtor da classe recebe agora um optional de Int que tem por padrão nil, caso seja nil ele então retorna 1/3 do número de bolas contidos no Range.
